### PR TITLE
email regular expression should accept xx-xxx@xxxx.

### PR DESCRIPTION
**Pull request by iewgnid**
- is common for email address.

### CODE REVIEW

**Comment by dengliming** [comment]
This is a simpler way.
`/^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/`

**Comment by iewgnid** [comment]
> This is a simpler way.
> `/^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/`

`/^[A-Za-z0-9_\-\.]+\@[A-Za-z0-9_\-\.]+\.[A-Za-z]{2,4}$/`
can even remove `(` and `)` XD

**Comment by iewgnid** [comment]
and noticed another thing, domain part `{2,4}` can simply replace to `+` or `{2,}`.  
because some new domains will be checked. for example `xxx.asia`.

**Comment by iewgnid** [comment]
> and noticed another thing, domain part `{2,4}` can simply replace to `+` or `{2,}`.
> because some new domains will be checked. for example `xxx.asia`.

sorry, `xxx.asia` is cool. `xxx.tokyo` is not.

**Pull request closed without merging**
